---
# Source: solr-external/charts/solr/charts/zookeeper/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-zookeeper
  namespace: default
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.9.3
    helm.sh/chart: zookeeper-13.7.2
    app.kubernetes.io/component: zookeeper
    role: zookeeper
automountServiceAccountToken: false
