creation_rules:
  - path_regex: secrets/secrets.enc.yaml
    encrypted_regex: "^.*(user|password|token)"
    age: >-
      age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4,
      age1cejryeahwwgvwwqq9kcjarw9k9wuxm52uxaapr22mrphsa5q6f5q83rmwu

