---
# Source: solr/charts/zookeeper/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: solr-zookeeper
  namespace: default
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.9.3
    helm.sh/chart: zookeeper-13.7.2
    app.kubernetes.io/component: zookeeper
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: solr
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/component: zookeeper
