---
# Source: solr/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: solr
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: 9.8.0
    helm.sh/chart: solr-9.5.3
    app.kubernetes.io/component: solr
  namespace: "default"
type: Opaque
data:
  solr-password: "PASSWORD"
