apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-workflows/tree/v3.6.2/manifests/base
- https://github.com/argoproj/argo-workflows/tree/v3.6.2/manifests/cluster-install/workflow-controller-rbac
- https://github.com/argoproj/argo-workflows/tree/v3.6.2/manifests/cluster-install/argo-server-rbac

namespace: argo
