apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - "https://github.com:argoproj/argo-workflows/manifests/cluster-install/workflow-controller-rbac?ref=v3.6.2"
  - "https://github.com:argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac?ref=v3.6.2"
  - ./service-account-token.yaml
namespace: argo
