apiVersion: v1
kind: Secret
metadata:
    name: example-secret
    namespace: default
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:s+D95HMD+MdMXICQLZg0wMFmPr0tczUq/igf3tdrUg==,iv:llhVGpswN8AS+EVVF9WeEFsd/R6DjvDWDAmzCaKTvsI=,tag:qgKRy2/FZzyXxu6N+vgvUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeXBxRkJ1bGhYbncxb2Vi
            WkcxKzYxVElmbTkxMFZBSnp6NElLUE4vb0dJCmRPd2lpMGxCN244R3NpVGtBRW1u
            blpPS25NNlBwWHNWSzZDcHZsM1U1eWcKLS0tIHBQTlRMU3hCVC9CSkRaMnhNQzha
            cUZZd0tiYTlyTmNXYjhKbk5QTVN4UEEKMnCIU7K2UuRWEdIKiov0o1YBJRa/fMqh
            OskjHzdSgZKBBUQIOHn/xOCdm0ESMxjqhGY9UjoOBZ4+2/ClWx6xZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cejryeahwwgvwwqq9kcjarw9k9wuxm52uxaapr22mrphsa5q6f5q83rmwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1N5TDRnNDgvSzJCMmFK
            YjJZM3MzSHZpeEVoeVg0NWF4ZWlaWG9OUlNJCjgvZ0RFWDlpY3B2TDRYSncxQmMr
            R3JwMW1jYjlLdG1aRTZVTjM5WU1mS2cKLS0tIDZvcmxVM2toUExLZ1k5VytSM3pC
            QXU2czY0cWp2Q2N3Tkp0dFhxMGZ3QUkK/UD2D1ZOA+RN4r/6YzYWKFwqp6Q9bJCb
            mSucrgcKPP4etUzTiVBASLU6X3WMzd1V7vr5NLDq15oUi6+JihlXxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T14:12:58Z"
    mac: ENC[AES256_GCM,data:lT0xqD782vFKfd4m9UjGBB3k2Sgn3duJvGJTtBfEhafnspUVGlq8l/+I3hV1dfRros4T+bPELmE0fspvdwspQ654A8YmnMfMK7sKU2Jf+ZwrQtkGWUkGCKMJMMXW5Jo74Iu7m+a4tbe56WHiGIs2jTqJVgAVPDKaX2IcLRt7X0E=,iv:gLOpq51Hmfq1jWCAMOpTDuIVic//N/J+Z08t0c12wFk=,tag:RmbfwbxbO5JrVLimvH9lSA==,type:str]
    pgp: []
    encrypted_regex: ^.*(user|password|token)
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: example-secret2
    namespace: default
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:wIWwOInMuC4wmIPPIe53/4/mD22ovrBqA3cCSpGVXA==,iv:M3NS6kAj+szhPo1y0dbjVPwLxQ8PRPh8Evip0/qXDEI=,tag:y5pdfDIWYKVOxPxIDB/IzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeXBxRkJ1bGhYbncxb2Vi
            WkcxKzYxVElmbTkxMFZBSnp6NElLUE4vb0dJCmRPd2lpMGxCN244R3NpVGtBRW1u
            blpPS25NNlBwWHNWSzZDcHZsM1U1eWcKLS0tIHBQTlRMU3hCVC9CSkRaMnhNQzha
            cUZZd0tiYTlyTmNXYjhKbk5QTVN4UEEKMnCIU7K2UuRWEdIKiov0o1YBJRa/fMqh
            OskjHzdSgZKBBUQIOHn/xOCdm0ESMxjqhGY9UjoOBZ4+2/ClWx6xZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cejryeahwwgvwwqq9kcjarw9k9wuxm52uxaapr22mrphsa5q6f5q83rmwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1N5TDRnNDgvSzJCMmFK
            YjJZM3MzSHZpeEVoeVg0NWF4ZWlaWG9OUlNJCjgvZ0RFWDlpY3B2TDRYSncxQmMr
            R3JwMW1jYjlLdG1aRTZVTjM5WU1mS2cKLS0tIDZvcmxVM2toUExLZ1k5VytSM3pC
            QXU2czY0cWp2Q2N3Tkp0dFhxMGZ3QUkK/UD2D1ZOA+RN4r/6YzYWKFwqp6Q9bJCb
            mSucrgcKPP4etUzTiVBASLU6X3WMzd1V7vr5NLDq15oUi6+JihlXxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T14:12:58Z"
    mac: ENC[AES256_GCM,data:lT0xqD782vFKfd4m9UjGBB3k2Sgn3duJvGJTtBfEhafnspUVGlq8l/+I3hV1dfRros4T+bPELmE0fspvdwspQ654A8YmnMfMK7sKU2Jf+ZwrQtkGWUkGCKMJMMXW5Jo74Iu7m+a4tbe56WHiGIs2jTqJVgAVPDKaX2IcLRt7X0E=,iv:gLOpq51Hmfq1jWCAMOpTDuIVic//N/J+Z08t0c12wFk=,tag:RmbfwbxbO5JrVLimvH9lSA==,type:str]
    pgp: []
    encrypted_regex: ^.*(user|password|token)
    version: 3.7.3
