apiVersion: v1
kind: Secret
metadata:
    name: example-secret
    namespace: default
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:48/W4eWxcKBWN3zzTppIJeeln0Gn4PcmKgoWjP/grg==,iv:0gJq+VkfuoINttuDhmXTT7RrDR+pM445oGj1e1ItgyI=,tag:8nSGEeyN75lgAQwL8eV7hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dGg0MWhKMUp2TEpka1pt
            eTRWSy8xM2todWFNUlByRjhvc3E1a2hIRlE0ClFCUEwzaCtROEhZTWR5RWZmcC9h
            d25rZ0licVIxYzJIYUNjK3cwZkd5RUUKLS0tIEd3QlFkZW1wRGdrY2ROL0VKUXNv
            bUhNOXNwVDQ3NVFONHE3MmdsdVFGdVUKS2nsN1kLhP4xCUw6/GBH3Mj1di960Nve
            2guf8f8ErT5Z58ZAXN6jK/Oqee0udU65yQDIyN/2PbQb1tMdiOYs9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T15:37:38Z"
    mac: ENC[AES256_GCM,data:8YRkwY9B2SJek3TF8IFYz9vJdiMiLYwh605XRt9s7ylZw2zw69yfJKV0AcTHmFvprqPHCvVApCPWmlgS+eDPX0xKBOgJUNtfBIoluqxLBkjEp7Vsass90xZmpyBM8xjU8AS+4PG8Lw28Fqov0eqTc7VWj7WWEAnbku8DzKBongM=,iv:enWrd05PoJfO4ttVLIo094D/YacBZ4jOKqfsVi890A0=,tag:vi7rZ610E3/vhXayLe4sYQ==,type:str]
    pgp: []
    encrypted_regex: ^.*(user|password|token)
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: example-secret2
    namespace: default
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:DDifKQhNPKlTGb0ETiI3TfdIUy6k9ih6xOu5a1wDdg==,iv:R5BTHBkq/v3VFQ2yg9mODinE4NBTCLRo4UJeNb980ug=,tag:5pT4zMrT818MpuZgdnsV4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dGg0MWhKMUp2TEpka1pt
            eTRWSy8xM2todWFNUlByRjhvc3E1a2hIRlE0ClFCUEwzaCtROEhZTWR5RWZmcC9h
            d25rZ0licVIxYzJIYUNjK3cwZkd5RUUKLS0tIEd3QlFkZW1wRGdrY2ROL0VKUXNv
            bUhNOXNwVDQ3NVFONHE3MmdsdVFGdVUKS2nsN1kLhP4xCUw6/GBH3Mj1di960Nve
            2guf8f8ErT5Z58ZAXN6jK/Oqee0udU65yQDIyN/2PbQb1tMdiOYs9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T15:37:38Z"
    mac: ENC[AES256_GCM,data:8YRkwY9B2SJek3TF8IFYz9vJdiMiLYwh605XRt9s7ylZw2zw69yfJKV0AcTHmFvprqPHCvVApCPWmlgS+eDPX0xKBOgJUNtfBIoluqxLBkjEp7Vsass90xZmpyBM8xjU8AS+4PG8Lw28Fqov0eqTc7VWj7WWEAnbku8DzKBongM=,iv:enWrd05PoJfO4ttVLIo094D/YacBZ4jOKqfsVi890A0=,tag:vi7rZ610E3/vhXayLe4sYQ==,type:str]
    pgp: []
    encrypted_regex: ^.*(user|password|token)
    version: 3.7.3
