apiVersion: v1
kind: Secret
metadata:
    name: example-secret
    namespace: default
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:AdyR+WKQsywt9ZhmkL33EAMFdpnx2E3XcC91zgYfz6DoO79pQVNa4K9H+dU=,iv:/lz5Ka30FfTpfGwtnI6TjTA4Q4lqGrdHRhy/7omoL2Q=,tag:mZnWCGEAb6dE844lte+9TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa1lNWjA2Y2dXZ1lLWFJX
            VmNDcXpleEdwalg0TzZ6TkM1bVN6ZlFSY2lrCkRlNGhpZTBvQ0hwTlJNV21tc1BV
            NEJnR3FFaTJhUHJIdFF0djhaZldFUGcKLS0tIE5iWEh2WllMY0ZvM3NMV3AxOTIv
            OS9yK2dqRmNtQ21HdE15STZ0SzVXdE0Kt1RpAbgd8hbEOH2Kv4OD4mgHpOq1pGbC
            xyBGFXIEN5SIdF6uKkP7G3LU2/dJGTa7AVAsgygxUTxWiNb+o0APbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107e7w608czn3n7hquwe49g5589yzwrtd7dcll9g9d9uvnhqnldgsvr8fsh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTEpWd24vZ2pQblQwbGRR
            Mjl0L1pncmtQVkl5VnJMZkxvTWwxV2gvNFJzClJ3cHozZjlTMkpNamVSS1dDMVdO
            cjFGbGV1VVhSV2h5MnVaWmhUQm40MlUKLS0tIElGd0hVbmtDbHMzT1VLUzE0V1JO
            d1d0ejQ5YnBDajVlRUlGMHQ0UWF4aTgKRC5KSIohHPYWt4fx1rME6j+sXBRrynJL
            Z/j3M4xDYYc70i8GQEE8Y3Yekbh0T+WwlT44rnLC+I0/CbA9j3yjHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T15:49:11Z"
    mac: ENC[AES256_GCM,data:fsFmyYIOAeWb/AFVaImHe5CpRvfeXbumSfjIPhWwlQ8SeMafrw8kJXfhzUj+RdpGHNcnERztopLVjlZTY9LW6WEYhKCCYk53p0B4mG5uWwBkZ3Fk8kWQ+1yTaz5SywIWiflb49aj+ur87x8pll6Rc8YgwEvZVw54PegygvpgYpg=,iv:R7u6LtseqI0ak8B3RPiRg5kRe1gp/LpU1pl3uVsH1cQ=,tag:cQWwHtHJiwQQ4EersHlYBg==,type:str]
    pgp: []
    encrypted_regex: ^.*(user|password|token|key)
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: example-secret2
    namespace: default
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:YaOihH+SzBkMXmskbWWDCbtnlq97IzLaDdIb06Xx2DhdceAChbUdBN/+myo=,iv:uEGrtXubDCnWAeCNXL69f3mfCtp70siGfGG/W62+Woc=,tag:xd2TK71n6zIfX6WoJa0mAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa1lNWjA2Y2dXZ1lLWFJX
            VmNDcXpleEdwalg0TzZ6TkM1bVN6ZlFSY2lrCkRlNGhpZTBvQ0hwTlJNV21tc1BV
            NEJnR3FFaTJhUHJIdFF0djhaZldFUGcKLS0tIE5iWEh2WllMY0ZvM3NMV3AxOTIv
            OS9yK2dqRmNtQ21HdE15STZ0SzVXdE0Kt1RpAbgd8hbEOH2Kv4OD4mgHpOq1pGbC
            xyBGFXIEN5SIdF6uKkP7G3LU2/dJGTa7AVAsgygxUTxWiNb+o0APbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107e7w608czn3n7hquwe49g5589yzwrtd7dcll9g9d9uvnhqnldgsvr8fsh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTEpWd24vZ2pQblQwbGRR
            Mjl0L1pncmtQVkl5VnJMZkxvTWwxV2gvNFJzClJ3cHozZjlTMkpNamVSS1dDMVdO
            cjFGbGV1VVhSV2h5MnVaWmhUQm40MlUKLS0tIElGd0hVbmtDbHMzT1VLUzE0V1JO
            d1d0ejQ5YnBDajVlRUlGMHQ0UWF4aTgKRC5KSIohHPYWt4fx1rME6j+sXBRrynJL
            Z/j3M4xDYYc70i8GQEE8Y3Yekbh0T+WwlT44rnLC+I0/CbA9j3yjHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T15:49:11Z"
    mac: ENC[AES256_GCM,data:fsFmyYIOAeWb/AFVaImHe5CpRvfeXbumSfjIPhWwlQ8SeMafrw8kJXfhzUj+RdpGHNcnERztopLVjlZTY9LW6WEYhKCCYk53p0B4mG5uWwBkZ3Fk8kWQ+1yTaz5SywIWiflb49aj+ur87x8pll6Rc8YgwEvZVw54PegygvpgYpg=,iv:R7u6LtseqI0ak8B3RPiRg5kRe1gp/LpU1pl3uVsH1cQ=,tag:cQWwHtHJiwQQ4EersHlYBg==,type:str]
    pgp: []
    encrypted_regex: ^.*(user|password|token|key)
    version: 3.7.3
